commonConfig: 
            appName: spring-boot-practice


# tomcat 配置
#server.address: 
server:
      port: 8989
      contextPath:  /springBoot
      displayName:  spring-boot-practice   
# 日志配置
logging:
        file: ${commonConfig.appName}.log
        path: ./
        pattern:
                console: "-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}  [%F:%L]  %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
                
                file: "${WHO}  %d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{60}   [%F:%L]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
                
                
        level:  
            root: INFO
